project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on Ex/Hands-on Ex 1/Hands-on Exercise 1.html
      - text: In-class Exercises
        menu: 
          - text: In-class Exercise 1
            href: In-class Ex/In-class Ex1/In-class_Ex1_demo.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

