project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on Ex/Hands-on Ex 1/Hands-on Exercise 1.html
          - text: Hands-on Exercise 2A
            href: Hands-on Ex/Hands-on Ex 2/Hands-on Exercise 2A.html
          - text: Hands-on Exercise 2B
            href: Hands-on Ex/Hands-on Ex 2/Hands-on Exercise 2B.html
          - text: Hands-on Exercise 2C
            href: Hands-on Ex/Hands-on Ex 2/Hands-on Exercise 2C.html
          - text: Hands-on Exercise 3
            href: Hands-on Ex/Hands-on Ex 3/Hands-on_Ex_3.html 
      - text: In-class Exercises
        menu: 
          - text: "In-class Exercise 1"
            href: In-class Ex/In-class Ex1/In-class_Ex1_demo.html
          - text: "In-class Exercise 2: Spatial Weights"
            href: In-class Ex/In-class_Ex2/In-class Ex_2_Spatial-Weights.html
          - text: "In-class Exercise 2: Global and Local Measures of Spatial Association - sfdep methods"
            href: In-class Ex/In-class_Ex2/In-class Ex_2_Global_Local_Measures.html
          - text: "In-class Exercise 2: Emerging Hot Spot Analysis: sfdep methods"
            href: In-class Ex/In-class_Ex2/In-class Ex_2_EHSA.html
          - text: "In-class Exercise 3: Calibrating Spatial Interaction Models with R"
            href: In-class Ex/In-class_Ex3/In-class_Ex3.html  
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
            href: Take-home Ex/Take-home Ex 1/Take-home_Exercise_1.html
          - text: Take-home Exercise 2
            href: Take-home Ex/Take-home Ex 2/Take-home_Ex_2.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

